name: freezed_sample
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.3

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  lints: ^1.0.0
